// Auth Types
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH';
export const AUTH_SET_BIOMETRIC = 'AUTH_SET_BIOMETRIC';

// Attendance Types
export const ATTENDANCE_PUNCH_IN = 'ATTENDANCE_PUNCH_IN';
export const ATTENDANCE_PUNCH_OUT = 'ATTENDANCE_PUNCH_OUT';
export const ATTENDANCE_HISTORY = 'ATTENDANCE_HISTORY';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';

// UI Types
export const UI_SET_LOADING = 'UI_SET_LOADING';

// Auth Action Types
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const BIOMETRIC_LOGIN_REQUEST = 'BIOMETRIC_LOGIN_REQUEST';
export const BIOMETRIC_LOGIN_SUCCESS = 'BIOMETRIC_LOGIN_SUCCESS';
export const BIOMETRIC_LOGIN_FAIL = 'BIOMETRIC_LOGIN_FAIL';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const LOGOUT = 'LOGOUT';
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const SET_BIOMETRIC_AVAILABLE = 'SET_BIOMETRIC_AVAILABLE';

// UI Action Types
export const UI_SET_ALERT = 'UI_SET_ALERT';
export const UI_HIDE_ALERT = 'UI_HIDE_ALERT';

// Punch In/Out types
export const PUNCH_IN_REQUEST = 'PUNCH_IN_REQUEST';
export const PUNCH_IN_SUCCESS = 'PUNCH_IN_SUCCESS';
export const PUNCH_IN_FAIL = 'PUNCH_IN_FAIL';

export const PUNCH_OUT_REQUEST = 'PUNCH_OUT_REQUEST';
export const PUNCH_OUT_SUCCESS = 'PUNCH_OUT_SUCCESS';
export const PUNCH_OUT_FAIL = 'PUNCH_OUT_FAIL';

// History types
export const ATTENDANCE_HISTORY_REQUEST = 'ATTENDANCE_HISTORY_REQUEST';
export const ATTENDANCE_HISTORY_SUCCESS = 'ATTENDANCE_HISTORY_SUCCESS';
export const ATTENDANCE_HISTORY_FAIL = 'ATTENDANCE_HISTORY_FAIL';

// Today's attendance types
export const TODAY_ATTENDANCE_REQUEST = 'TODAY_ATTENDANCE_REQUEST';
export const TODAY_ATTENDANCE_SUCCESS = 'TODAY_ATTENDANCE_SUCCESS';
export const TODAY_ATTENDANCE_FAIL = 'TODAY_ATTENDANCE_FAIL';

// Stats types
export const ATTENDANCE_STATS_REQUEST = 'ATTENDANCE_STATS_REQUEST';
export const ATTENDANCE_STATS_SUCCESS = 'ATTENDANCE_STATS_SUCCESS';
export const ATTENDANCE_STATS_FAIL = 'ATTENDANCE_STATS_FAIL';

// Break types
export const BREAK_IN_REQUEST = 'BREAK_IN_REQUEST';
export const BREAK_IN_SUCCESS = 'BREAK_IN_SUCCESS';
export const BREAK_IN_FAIL = 'BREAK_IN_FAIL';

export const BREAK_OUT_REQUEST = 'BREAK_OUT_REQUEST';
export const BREAK_OUT_SUCCESS = 'BREAK_OUT_SUCCESS';
export const BREAK_OUT_FAIL = 'BREAK_OUT_FAIL';

// Clear state
export const CLEAR_ATTENDANCE_STATE = 'CLEAR_ATTENDANCE_STATE';

export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST';
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS';
export const APPLY_LEAVE_FAIL = 'APPLY_LEAVE_FAIL';

export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST';
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS';
export const EMPLOYEE_PROFILE_FAIL = 'EMPLOYEE_PROFILE_FAIL';