// Auth Types
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH';
export const AUTH_SET_BIOMETRIC = 'AUTH_SET_BIOMETRIC';

// Attendance Types
export const ATTENDANCE_PUNCH_IN = 'ATTENDANCE_PUNCH_IN';
export const ATTENDANCE_PUNCH_OUT = 'ATTENDANCE_PUNCH_OUT';
export const ATTENDANCE_HISTORY = 'ATTENDANCE_HISTORY';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';

// UI Types
export const UI_SET_LOADING = 'UI_SET_LOADING';

// Auth Action Types
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const BIOMETRIC_LOGIN_REQUEST = 'BIOMETRIC_LOGIN_REQUEST';
export const BIOMETRIC_LOGIN_SUCCESS = 'BIOMETRIC_LOGIN_SUCCESS';
export const BIOMETRIC_LOGIN_FAIL = 'BIOMETRIC_LOGIN_FAIL';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const LOGOUT = 'LOGOUT';
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const SET_BIOMETRIC_AVAILABLE = 'SET_BIOMETRIC_AVAILABLE';

// UI Action Types
export const UI_SET_ALERT = 'UI_SET_ALERT';
export const UI_HIDE_ALERT = 'UI_HIDE_ALERT';

// Punch In/Out types
export const PUNCH_IN_REQUEST = 'PUNCH_IN_REQUEST';
export const PUNCH_IN_SUCCESS = 'PUNCH_IN_SUCCESS';
export const PUNCH_IN_FAIL = 'PUNCH_IN_FAIL';

export const PUNCH_OUT_REQUEST = 'PUNCH_OUT_REQUEST';
export const PUNCH_OUT_SUCCESS = 'PUNCH_OUT_SUCCESS';
export const PUNCH_OUT_FAIL = 'PUNCH_OUT_FAIL';

// History types
export const ATTENDANCE_HISTORY_REQUEST = 'ATTENDANCE_HISTORY_REQUEST';
export const ATTENDANCE_HISTORY_SUCCESS = 'ATTENDANCE_HISTORY_SUCCESS';
export const ATTENDANCE_HISTORY_FAIL = 'ATTENDANCE_HISTORY_FAIL';

// Today's attendance types
export const TODAY_ATTENDANCE_REQUEST = 'TODAY_ATTENDANCE_REQUEST';
export const TODAY_ATTENDANCE_SUCCESS = 'TODAY_ATTENDANCE_SUCCESS';
export const TODAY_ATTENDANCE_FAIL = 'TODAY_ATTENDANCE_FAIL';

// Stats types
export const ATTENDANCE_STATS_REQUEST = 'ATTENDANCE_STATS_REQUEST';
export const ATTENDANCE_STATS_SUCCESS = 'ATTENDANCE_STATS_SUCCESS';
export const ATTENDANCE_STATS_FAIL = 'ATTENDANCE_STATS_FAIL';

// Break types
export const BREAK_IN_REQUEST = 'BREAK_IN_REQUEST';
export const BREAK_IN_SUCCESS = 'BREAK_IN_SUCCESS';
export const BREAK_IN_FAIL = 'BREAK_IN_FAIL';

export const BREAK_OUT_REQUEST = 'BREAK_OUT_REQUEST';
export const BREAK_OUT_SUCCESS = 'BREAK_OUT_SUCCESS';
export const BREAK_OUT_FAIL = 'BREAK_OUT_FAIL';

// Clear state
export const CLEAR_ATTENDANCE_STATE = 'CLEAR_ATTENDANCE_STATE';

export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST';
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS';
export const APPLY_LEAVE_FAIL = 'APPLY_LEAVE_FAIL';

export const FETCH_LEAVES_REQUEST = 'FETCH_LEAVES_REQUEST';
export const FETCH_LEAVES_SUCCESS = 'FETCH_LEAVES_SUCCESS';
export const FETCH_LEAVES_FAIL = 'FETCH_LEAVES_FAIL';

export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST';
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS';
export const EMPLOYEE_PROFILE_FAIL = 'EMPLOYEE_PROFILE_FAIL';

// KRA Types
export const FETCH_KRA_REQUEST = 'FETCH_KRA_REQUEST';
export const FETCH_KRA_SUCCESS = 'FETCH_KRA_SUCCESS';
export const FETCH_KRA_FAIL = 'FETCH_KRA_FAIL';

export const FETCH_KRA_BY_ID_REQUEST = 'FETCH_KRA_BY_ID_REQUEST';
export const FETCH_KRA_BY_ID_SUCCESS = 'FETCH_KRA_BY_ID_SUCCESS';
export const FETCH_KRA_BY_ID_FAIL = 'FETCH_KRA_BY_ID_FAIL';

export const UPDATE_KRA_METRIC_REQUEST = 'UPDATE_KRA_METRIC_REQUEST';
export const UPDATE_KRA_METRIC_SUCCESS = 'UPDATE_KRA_METRIC_SUCCESS';
export const UPDATE_KRA_METRIC_FAIL = 'UPDATE_KRA_METRIC_FAIL';

// Employee Types
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAIL = 'FETCH_EMPLOYEES_FAIL';

// Meeting Types
export const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAIL = 'CREATE_MEETING_FAIL';

export const FETCH_MEETINGS_REQUEST = 'FETCH_MEETINGS_REQUEST';
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS';
export const FETCH_MEETINGS_FAIL = 'FETCH_MEETINGS_FAIL';

export const UPDATE_MEETING_STATUS_REQUEST = 'UPDATE_MEETING_STATUS_REQUEST';
export const UPDATE_MEETING_STATUS_SUCCESS = 'UPDATE_MEETING_STATUS_SUCCESS';
export const UPDATE_MEETING_STATUS_FAIL = 'UPDATE_MEETING_STATUS_FAIL';

// Create Expense
export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL';

// Fetch Expenses
export const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_FAIL = 'FETCH_EXPENSES_FAIL';

// Fetch Single Expense
export const FETCH_EXPENSE_BY_ID_REQUEST = 'FETCH_EXPENSE_BY_ID_REQUEST';
export const FETCH_EXPENSE_BY_ID_SUCCESS = 'FETCH_EXPENSE_BY_ID_SUCCESS';
export const FETCH_EXPENSE_BY_ID_FAIL = 'FETCH_EXPENSE_BY_ID_FAIL';

// Update Expense
export const UPDATE_EXPENSE_REQUEST = 'UPDATE_EXPENSE_REQUEST';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_FAIL = 'UPDATE_EXPENSE_FAIL';

// Delete Expense
export const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL';

export const PUNCH_IN_CANCEL = 'PUNCH_IN_CANCEL';
export const PUNCH_OUT_CANCEL = 'PUNCH_OUT_CANCEL';

